name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: 14

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Run npm install
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_PAT }} # Personal Access Token to use packages from Github Registry
      - name: Run npm test
        run: npm run test:unit
      - name: Save coverage artifact
        uses: actions/upload-artifact@v2
        with:
          name: lcov
          path: coverage/lcov.info
